# Generated by Django 5.2.14 on 2026-05-15 14:45

import apps.couples.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(db_index=True, default=apps.couples.models.generate_room_code, max_length=8, unique=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('compatibility_score', models.PositiveIntegerField(default=50)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('last_played_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'couple',
                'verbose_name_plural': 'couples',
            },
        ),
    ]
