# Generated by Django 5.2.14 on 2026-05-15 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couples_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='couple',
            name='user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couples_as_user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
