# Generated by Django 5.2.14 on 2026-07-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couples', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='is_long_distance',
            field=models.BooleanField(default=False, verbose_name='Relation à distance'),
        ),
        migrations.AddField(
            model_name='couple',
            name='relationship_duration',
            field=models.CharField(choices=[('less_than_1_year', "Moins d'un an"), ('1_to_3_years', '1 à 3 ans'), ('more_than_3_years', 'Plus de 3 ans'), ('engaged', 'Fiancés')], default='less_than_1_year', max_length=32, verbose_name='Durée de la relation'),
        ),
        migrations.AddField(
            model_name='couple',
            name='residence_continent',
            field=models.CharField(choices=[('africa', 'Afrique'), ('europe', 'Europe'), ('north_america', 'Amérique du Nord'), ('south_america', 'Amérique du Sud'), ('asia', 'Asie'), ('oceania', 'Océanie')], default='africa', max_length=32, verbose_name='Continent de résidence'),
        ),
    ]
