# Generated by Django 5.2.14 on 2026-05-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_granted', models.PositiveIntegerField(default=3)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('ad_network', models.CharField(default='rewarded', max_length=32)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('free', 'Gratuit'), ('premium', 'Premium Couple'), ('expired', 'Expiré')], default='free', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
