# Generated by Django 5.2.14 on 2026-05-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_kibawallet_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'abonnement couple', 'verbose_name_plural': 'abonnements couple'},
        ),
        migrations.AlterField(
            model_name='adreward',
            name='ad_network',
            field=models.CharField(default='simulated', max_length=32),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID transaction KibaWallet', max_length=128),
        ),
    ]
