# Generated by Django 5.2.14 on 2026-05-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('guess_text', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reaction', models.CharField(blank=True, max_length=8)),
            ],
            options={
                'verbose_name': 'réponse',
                'verbose_name_plural': 'réponses',
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('emoji', models.CharField(default='🏆', max_length=8)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CoupleBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('questions_played', models.PositiveIntegerField(default=0)),
                ('bonus_from_ads', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'usage quotidien',
                'verbose_name_plural': 'usages quotidiens',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_question_index', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('lobby', 'En attente'), ('question', 'Question active'), ('waiting_reveal', 'En attente reveal'), ('reveal', 'Révélation'), ('finished', 'Terminée')], default='lobby', max_length=24)),
                ('game_mode', models.CharField(choices=[('secret_answer', 'Réponse secrète'), ('guess_partner', 'Deviner le partenaire'), ('timed', 'Chronométré'), ('challenge', 'Défi couple'), ('compatibility', 'Compatibilité émotionnelle')], default='secret_answer', max_length=32)),
                ('category_filter', models.CharField(blank=True, choices=[('romantic', 'Romantique'), ('funny', 'Drôle'), ('spicy', 'Spicy'), ('deep', 'Conversations profondes'), ('know_partner', 'Connaissance du partenaire'), ('future', 'Futur du couple'), ('habits', 'Habitudes relationnelles')], max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'session de jeu',
                'verbose_name_plural': 'sessions de jeu',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('romantic', 'Romantique'), ('funny', 'Drôle'), ('spicy', 'Spicy'), ('deep', 'Conversations profondes'), ('know_partner', 'Connaissance du partenaire'), ('future', 'Futur du couple'), ('habits', 'Habitudes relationnelles')], db_index=True, max_length=32)),
                ('spicy_level', models.PositiveSmallIntegerField(default=0)),
                ('game_mode', models.CharField(choices=[('secret_answer', 'Réponse secrète'), ('guess_partner', 'Deviner le partenaire'), ('timed', 'Chronométré'), ('challenge', 'Défi couple'), ('compatibility', 'Compatibilité émotionnelle')], default='secret_answer', max_length=32)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['-created_at'],
            },
        ),
    ]
