# Generated by Django 5.2.14 on 2026-05-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='reaction',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
